[workspace]
resolver = "2"
members = ["example", "gui", "entrace_core", "bench", "entrace_query", "entrace_script"]

[profile.profiling]
inherits = 'release'
debug = true

# Optimize all dependencies even in debug builds:
[profile.dev.package."*"]
opt-level = 2
